### ISSUE TITLE
DJIBaseProductDelegate's productConnected() is not being called

### ISSUE THREAD

**Issue by aquilaseye** [dji-sdk/Mobile-SDK-iOS#100]
I'm writing my DJI app in Swift and came across the following problem when going through halfway in the tutorial "Creating a Camera Application". I made my ViewController class conform to the DJIVideoFeedListener, DJISDKManagerDelegate, DJIBaseProductDelegate, and the DJICameraDelegate. I properly registered my app successfully with the DJISDKManager.registerApp(with: self) method. I called the DJISDKManager.startConnectionToProduct() method. Then, the productConnected() method was implemented and for some reason the method is not being called. I put a breakpoint inside this productConnected() method to be sure and it is not being called.

To even further test this, I put some test code in the following method:
```
   func videoFeed(_ videoFeed: DJIVideoFeed, didUpdateVideoData videoData: Data) {
        if let product = DJISDKManager.product() {
            print("CONNECTED")
        }
      ...
}
```

Since I know that videoFeed(:didUpdateVideoData:) is being called, I wanted to check if DJISDKManager.product() is null. Sure enough, it is null and the above test code does not execute. I called the DJISDKManager.registerApp() and DJISDKManager.startConnectionToProduct(), so I don't know what could be going wrong. The video feed is showing correctly when I run the app but, I have no access to a DJICamera object since DJISDKManager.product() is always null and productConnected() never executes.

I'm coding this in Swift, with DJI iOS SDK v4.0 on a Phantom 3 Standard. The iOS version is 10.3.1 on an iPhone 5S with XCode 8.3.2. 
------
Here's my entire code in my ViewController class:
```
//
//  ViewController.swift
//  DJIDataReceiver
//
//  Created by aquilaseye on 4/30/17.
//  Copyright © 2017 aquilaseye. All rights reserved.
//

import UIKit
import DJISDK
import VideoPreviewer

class ViewController: UIViewController, DJIVideoFeedListener, DJISDKManagerDelegate, DJIBaseProductDelegate, DJICameraDelegate {
    @IBOutlet weak var fpvView: UIView!
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        registerApp()
        
        VideoPreviewer.instance().setView(fpvView)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        VideoPreviewer.instance().setView(nil)
        DJISDKManager.videoFeeder()?.primaryVideoFeed.remove(self)
    }

    func registerApp() {
        DJISDKManager.registerApp(with: self)
    }
    
    func fetchCamera() -> DJICamera? {
        if let baseProduct = DJISDKManager.product() {
            if baseProduct is DJIAircraft {
                return (baseProduct as! DJIAircraft).camera
            }
            else if baseProduct is DJIHandheld {
                return (baseProduct as! DJIHandheld).camera
            }
        }
        
        return nil
    }
    
    // MARK: - DJISDKManagerDelegate methods

    func appRegisteredWithError(_ error: Error?) {
        var message = "Successful!"
        if let _ = error {
            message = "Enter the App Key."
        }
        else {
            DJISDKManager.startConnectionToProduct()
            DJISDKManager.videoFeeder()?.primaryVideoFeed.add(self, with: nil)
            VideoPreviewer.instance().start()
        }
        
        showAlertViewWithTitle("App Registration", with: message)
    }
    
    func showAlertViewWithTitle(_ title: String, with message: String) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let alertAction = UIAlertAction(title: "OK", style: .default, handler: nil)
        alert.addAction(alertAction)
        
        present(alert, animated: true, completion: nil)
    }
    
    // MARK: - DJIBaseProductDelegate methods

    func productConnected(_ product: DJIBaseProduct?) {
        // DOES NOT GET EXECUTED?
        if let baseProduct = product {
            baseProduct.delegate = self
            
            if let camera = fetchCamera() {
                camera.delegate = self
                
                // Change the camera mode to RecordVideo since it has a wider image
                weak var weakSelf = self
                camera.setMode(.recordVideo, withCompletion: {
                    error in
                    
                    if let error = error {
                        weakSelf?.showAlertViewWithTitle("Set DJICameraModeRecordVideo Failed!", with: error.localizedDescription)
                    }
                })
            }
        }
    }
    
    // MARK: - DJIVideoFeedListener
    
    func videoFeed(_ videoFeed: DJIVideoFeed, didUpdateVideoData videoData: Data) {
        
        if let product = DJISDKManager.product() {
            print("CONNECTED")
        }
        
        videoData.withUnsafeBytes {
            (ptr: UnsafePointer<UInt8>) in
            
            let mutablePointer = UnsafeMutablePointer(mutating: ptr)
            VideoPreviewer.instance().push(mutablePointer, length: Int32(videoData.count))
        }
    }
    
    // MARK: - DJICameraDelegate
    func camera(_ camera: DJICamera, didUpdate systemState: DJICameraSystemState) {
        // Empty for now
    }   
}
```

**Comment by athiercelin** [comment]
Thank you for the feedback.
Can you try again with SDK 4.0.1?

**Comment by dbaldwin** [comment]
@aquilaseye I had to hack around with this quite a bit last week and finally got productConnected to be called. I followed the structure of the DJI SDK Swift demo. We're currently rewriting DronePan and a couple other apps with SDK 4.0.1 and having all sorts of troubles. So I've put together a sample simulator app for our testing during the rewrite. Feel free to pull it and give it a run. You should see the product model get printed to the console and everything should work as expected. But one thing I'd like your feedback on is if you can get the video preview to work on the actual aircraft. For us it only works in the simulator when in bridge mode, but it does not work on the actual hardware! Crazy. Take a look and see if this helps: https://github.com/dbaldwin/DJISimulatorExample

**Comment by dbaldwin** [comment]
FYI I was able to get the video feed and camera object to work by doing the following with the DJISimulatorExample link I posted above:

1. Fire up P4 RC and aircraft

2. Open up app in iPad

3. Connect cable and everything worked as expected

@athiercelin can you confirm with the latest SDK that we still need to have the app open before connecting USB? I know this was the case with the beta SDK and am seeing similar behavior with SDK 4.0.1, at least for connecting to the camera. I can get location and altitude updates as well as the widgets are responding, but the camera does not seem to register unless I execute the steps above.

**Comment by XietongLU** [comment]
@dbaldwin the issue you mentioned may exist in 4.0 beta but it has been fixed in the official release of 4.0. I tested 4.0.1 and it works fine. 
The correct way to set the delegate of camera is: 
when the program is started and SDK is registered successfully, check if there is already connected camera component. If so, set the delegate. 
Then listen to 
- (void)componentConnectedWithKey:(NSString * _Nullable)key andIndex:(NSInteger)index; in DJISDKManagerDelegate. This will inform you the connectivity change of DJICamera. When DJICamera is reconnected, you have set the DJICameraDelegate again.

**Comment by aquilaseye** [comment]
Hey guys. So, I updated to 4.0.1 and it is still not calling the productConnected() method or even the componentConnected() method. Since I'm using a Phantom 3 Standard which does not require a USB connection to the RC unit and connects through Wi-Fi, could this be a problem?

**Comment by aquilaseye** [comment]
@XietongLU Sorry to ask but, is it possible to reopen this issue?

**Comment by dbaldwin** [comment]
@XietongLU it would be nice if there was an example that demonstrates what you're talking about. The current Obj-C and Swift examples make no use of componentConnected. Even the FPV demo app doesn't use it to set the delegate. It uses productConnected as shown here:

https://github.com/DJI-Mobile-SDK-Tutorials/iOS-FPVDemo/blob/master/FPVDemo/DJICameraViewController.m#L99-L108

**Comment by TalesGaleno** [comment]
Hello @aquilaseye , I am having some problems with Swift Programming on DJISDK, especially cause I don't know how to "translate" from OBJ-C to Swift. I've been stuck on this camera application for a while now and I would like to get some light. Could you help me on it?

**Comment by oliverou** [comment]
Hi @TalesGaleno, you can check this [Swift FPVDemo](https://github.com/DJI-Mobile-SDK-Tutorials/iOS-FPVDemo-Swift) for help. It's a swift version of FPVDemo published recently.

**Comment by TalesGaleno** [comment]
Im having problems when trying to compile it on Xcode, with the Mach-O
Linker Warning -read_only_relocs cannot be used with x86_64... How do I fix
it?


2017-05-26 5:25 GMT-03:00 欧泽林 <notifications@github.com>:

**Comment by dji-dev** [comment]
Hi @TalesGaleno , please use the latest Xcode 8.3.2 to compile the swift sample.

**Comment by TalesGaleno** [comment]
I've updated my Xcode to the latest version of 8.3.3 and it still gives me
the same error...

2017-06-01 11:53 GMT-03:00 DJI <notifications@github.com>:

**Comment by oliverou** [comment]
Hi @TalesGaleno, we have addressed the issue, will investigate it. Currently, it's a build warning, and won't affect your normal usage.

**Comment by sglushchenko** [comment]
Hi Guys. I try Swift FPVDemo. And productConnected don't called. I use Xcode 8.3.3. DJI-SDK-iOS (4.2). And Swift. My drone(Phantom 3 Standard) connected with cable to laptop, my iPad connected to laptop, RC don't connected. I use simulator. I can flight at simulator, it's ok. What I do wrong? Maybe need make release version of application or maybe anything else?

**Comment by sglushchenko** [comment]
I try disconnect all cable and try connect to Drone without simulator. Don't work. And when I launch DJI GO I see some stranges. For example, I see captured video, but I don't see battery level or another information. My Android device show all information, My iPad don't show. And at top left corner I see disconnected. And it's strange. I see video, but I disconnected and don't have any information. Maybe it help why I can't connect to device from My application

**Comment by oliverou** [comment]
Hi @sglushchenko , you should connect your iPad with Phantom 3 Standard RC's WiFi to debug your application, please check this documentation to learn how to connect and run application: [Connect Mobile Device and Run Application](http://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-run.html#connect-mobile-device-and-run-application).

**Comment by RTLcoil** [comment]
Hi guys. Can you help me. I developed application. All OK. I develop a lot of features. And test application at DJI Simulator. And I don't develop application 1 month. After it I think I update XCode And now I can't debug application at iPad. When iPad connected to Macbook by USB cabel iPad don't find Drone and don't connect to product. If I detach iPad all work good. Why it happens and how it fix? Because I can debug iOS application and implement new features.

**Comment by sglushchenko** [comment]
Hi guys. Can you help me. I developed application. All OK. I develop a lot of features. And test application at DJI Simulator. And I don't develop application 1 month. After it I think I update XCode And now I can't debug application at iPad. When iPad connected to Macbook by USB cabel iPad don't find Drone and don't connect to product. If I detach iPad all work good. Why it happens and how it fix? Because I can debug iOS application and implement new features.

**Comment by oliverou** [comment]
Hi @sglushchenko, could you tell us which DJI Product do you use for testing? Also, are you using the latest iOS SDK 4.2.2?

**Comment by sglushchenko** [comment]
Thank you for the answer @oliverou . I use phantom 3 standard, firmware 1.9.2, xcode 8.3.3, DJI SDK 4.2.2. for simulation I use DJI PC Simulator at VM fusion. And if I disconnecte my iPad from laptop then I can find product, connect and all work, sometimes I can't connect to battery or flightcontroller or airlink. Maybe it my drone broken. But it work previously and I can flight with remote controller at Simulator. And I can't launch waypoint mission. All it very strange for me.I'll try find another drone and test. But maybe you can help?

**Comment by oliverou** [comment]
Hi @sglushchenko, thanks for the feedbacks. We have addressed this issue and will fix it in the upcoming SDK version.

**Comment by sglushchenko** [comment]
@oliverou So it can be bug at SDK? And previously I used 4.2.1 SDK. And when I try start mission I see error
Command cannot be executed.(code:-5024)

I'm waiting when mission state will be "ready for execute" and after it I start mission. It can be because some components didn't found. How I said, sometimes SDK connect to product but can't find some component like battery, airlink or another component. Just need reregistration application and try connect again.

**Comment by KCPavana** [comment]
I am trying to connect Mavic Air using DJISDK.framework. After I call
DJISDKManager.startConnectionToProduct()
the following delegate method is not called.
productConnected(_ product: DJIBaseProduct?)

I am using DJI-SDK-iOS (4.8.1)

I am using iOS version 11.4.1
XCode version 10.0
