### ISSUE TITLE
Wrong script name

### ISSUE THREAD

**Issue by cloudqq** [dji-sdk/Mobile-SDK-iOS#13]
scrip-frameworks ==>   strip-frameworks.sh

**Comment by oliverou** [comment]
Hi, thanks for your comment, we have already fixed the problem and update the readme file.

**Comment by jocelynlih** [comment]
I'm still having issue with the updated script: build for release with error 
Frameworks/Realm.framework/strip-frameworks.sh: No such file or directory
Any thought on the error?

**Comment by zlinoliver** [comment]
Hi, please use 
~~~
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/DJISDK.framework/strip-frameworks.sh"
~~~
It should be DJISDK.framework. Already update the readme file, please check it. You can also check the Objective C sample project too. Hope this help!

**Comment by jocelynlih** [comment]
Thank you! It's working as expected now.

**Comment by dji-dev** [comment]
Hi jocelynlih, it seems that your problem is solved, let me close the issue, thanks!
