### ISSUE TITLE
DJIWaypointMissionOperator state unexpectedly changes from Executing to ReadyToUpload

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-iOS#193]
When using the latest version of the SDK (4.3.2), the DJIWaypointMissionOperator will sometimes fail to run an uploaded mission.  The mission loads and is uploaded without errors, and the call to start the mission returns without errors, but the DJIWaypointMissionOperator state will change from Executing to ReadyToUpload with NO ERRORS being reported through any listener or through any SDK call shortly after (within a few hundred milliseconds) the call to start the mission has returned.  I have not been able to track down exactly why this happens, but it happens quite often, enough so that we cannot actually ship a version of our app until we can track down why this is happening.

Any advice you can offer on how to fix this or if you can reproduce it will be greatly appreciated.

DJI iOS SDK version: 4.3.2
DJI Product: Phantom 4 Pro
iOS System version: 10.3.2
iOS Device type: iPad Air 2 (both simulated and actual device)
Xcode version: Xcode 8.3.3

**Comment by XietongLU** [comment]
@jgrantr is it a new issue since 4.3.2? Plz send us the flight log in the flight controller.

**Comment by jgrantr** [comment]
I'm not sure if it is new or just exacerbated in 4.3.2.  I would love to send you the flight log, but I'm not sure how to do that. I looked for some method on the DJIFlightController, but I didn't find anything.  What am I missing?

**Comment by wenqianqiao** [comment]
For the Flight Log:

First, you need to connect the drones to the PC or MAC.
Second, open the DJI Assistant2 and click on the flight data.
Third, a dialog pops up with the remind whether to enter the flight data mode. Click on Yes.
Fourth, then you could check there are a list of DAT file.   Enter the flight mode every time you finish the flight and compare the name of the DAT to find the latest one . Download and send it back to us.

**Comment by jdgolightly** [comment]
.dat file using the build, and directions from Grant from today. 12/05/2017 however the file size is 93MB compressed, how do you want us to send this file to you? I tried adding here and it threw an error stating try a file less than 10 MB.

**Comment by jgrantr** [comment]
@jdgolightly got that large file zipped up and we upload it to Dropbox.  You can access it here:

https://www.dropbox.com/s/xcb5h3mulgrtnnz/FLY420.DAT.zip?dl=0

**Comment by jgrantr** [comment]
@XietongLU @wenqianqiao Please let us know if you need anymore information. From our logging, the error occurred at 2017-12-05 13:21:37:464 -0700.

**Comment by jgrantr** [comment]
Just wondering if there is an update on this issue.  Was it fixed in 4.4?

**Comment by jdgolightly** [comment]
We had a new build from the 4.4. sdk release today, we're still seeing the issue. 
Here are the logs from 2 flights today that we're seeing the issue in.
DJISDKDebugLogs12.22.2017.zip

**Comment by wenqianqiao** [comment]
@jdgolightly  Hi jdgolightly, I also wonder what is the behavior of the drone itself after the successfully start the mission?

**Comment by wenqianqiao** [comment]
Hi Jdgolight, I just forwarded your dropbox flight log to our colleague and they didn't find any abnormal information on that. There are five flights which consists of 2 or 3 waypoints.

**Comment by lijia6745** [comment]
Did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
